/* eslint-disable @typescript-eslint/no-empty-interface */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* tslint:disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/
export interface IEducation {
  /**
   * Give a constant width to all logos to have nice allignment.
   */
  logoWidth?: number;
  /**
   * Used with format to allow you to configure date output.
   */
  dateFormat?: string;
  /**
   * The number of decimal points you want to output in gpa output
   */
  gpaPrecision?: number;
  /**
   * A list of schools that you want on your resume
   */
  schools: {
    /**
     * The name of the school you went to
     */
    name: string;
    /**
     * Your cumulative GPA for the school you went to
     */
    gpa?: number;
    /**
     * When you started at this institution
     */
    startDate?: Date;
    /**
     * When you finished at this institution (null for present)
     */
    endDate?: Date | null;
    /**
     * What was your major (if applicable) at this university
     */
    major?: string;
    /**
     * Any awards you want to brag about
     */
    awards?: string;
    /**
     * The url of where the image is located.
     */
    logoURL?: string;
    /**
     * The website of the institution. Will be hyperlinked on the logo and header
     */
    website?: string;
    /**
     * A named list of things you want to talk about
     */
    namedBlurbs?: {[k: string]: string};
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

export default IEducation;
