/* eslint-disable @typescript-eslint/no-empty-interface */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* tslint:disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/
export interface IHome {
  /**
   * Your name
   */
  name: string;
  /**
   * A little blurb under your name that defines your objectives
   */
  missionStatement?: string;
  /**
   * An image you want people to see on this landing page as a background
   */
  backgroundImageURL?: string;
  /**
   * The color of the background (like background image above)
   */
  backgroundColor?: string;
  [k: string]: unknown;
}

export default IHome;
